# Generated by Django 5.2.5 on 2025-08-22 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
